package com.article.metaphor.llm.processor.common.model;

public enum DocumentChunkStatus {

    PENDING,

    // lexical unit processing
    LEXICAL_UNIT_PROCESSING__PENDING,
    LEXICAL_UNIT_PROCESSING__IN_PROGRESS,
    LEXICAL_UNIT_PROCESSING__FAILED,

    // dictionary access
    DICTIONARY_ACCESS__PENDING,
    DICTIONARY_ACCESS__IN_PROGRESS,
    DICTIONARY_ACCESS__FAILED,

    // metaphor analysis
    METAPHOR_ANALYSIS__PENDING,
    METAPHOR_ANALYSIS__IN_PROGRESS,
    METAPHOR_ANALYSIS__FAILED,

    PENDING_REPROCESSING,
    SUCCESSFULLY_PROCESSED,
    NEXT_ATTEMPT_NEEDED,
    FAILED_TO_PROCESS
}
